server:
  port: 8088

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://your host:3306/luzhou-spa?serverTimezone=UTC&characterEncoding=utf8&useUnicode=true&useSSL=true
    username: root
    password: root
  redis:
    database: 0
    host: your host
    port: 7911
    password:
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
    timeout: 5000ms


#swagger配置
swagger:
  base-path: /**
  base-package: 'cn.hfanmo.lzspa'
  title: '庐州Spa-swagger文档'
  description: '庐州Spa后台接口详情'
  version: 'v0.0.1'
  contact:
    name: 'KasonZzz'
    url: 'http://www.cutenine.cn'
    email: 'jamobastow@gmail.com'



#  定时任务配置
scheduled:
  MySQL:
    DBC_DRIVER: com.mysql.cj.jdbc.Driver
    DB_URL: jdbc:mysql://localhost:3306/luzhou-spa?serverTimezone=UTC&characterEncoding=utf8&useUnicode=true&useSSL=true
    USERNAME: root
    PASSWORD: Root7911
  cron: 0/5 * * * * ?     #每月最后一天 10:15分执行 “ 0 15 10 L * ? ”
enable:
  scheduled: false



# mybatis-plus
mybatis-plus:
  type-aliases-package: cn.hfanmo.lzspa.pojo
  mapper-locations:  classpath*:mapper/*.xml
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#security:
#  basic:
#    enabled : false


ali:
  accessKey: "your sdk"
  secretKey: "your sdk"
  templateCode: "your sdk"
  signName: "your sdk"
  regionId: "cn-hangzhou"


qiniu:
  accessKey: "your sdk"
  secretKey: "your sdk"
  bucket: "your sdk"


#微信支付
appid: "your sdk"
partner: "your sdk"
partnerkey: "your sdk"
notifyurl: "your sdk"
